name: Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "17 5 * * 4"

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@99c09fe975337306107572b4fdf4db224cf8e2f2 # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@e5d2f324924c57b6cabef9bdd7a1c85d62a89be2 # v3.37.0
        with:
          sarif_file: results.sarif
